name: Deploy to CodeDeploy

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # BUILD STEPS HERE

      - name: Upload artifacts to S3
        run: aws s3 cp ../.. s3://infra-app-qa/

      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name codedeploy-app-qa \
            --deployment-group-name codedeploy-app-qa \
            --s3-location bucket=infra-app-qa,key=${{ github.workspace }}/../../*,bundleType=zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1