name: Deploy to CodeDeploy

on:
  push:
    branches: ["master"]

jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    steps:
      -
        name: Deploy the app
        run: |
            aws deploy create-deployment \
            --application-name codedeploy-app-qa \
            --deployment-group-name codedeploy-app-qa \
            --s3-location bucket=infra-app-qa,key=code-deploy.zip,bundleType=zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1